effect @p[scores={Pip=1}] haste 3 0 true
effect @p[scores={Pip=1}] jump_boost 3 0 true
effect @p[scores={Pip=1}] speed 3 0 true
effect @p[scores={Pip=2}] haste 3 1 true
effect @p[scores={Pip=2}] jump_boost 3 1 true
effect @p[scores={Pip=2}] speed 3 1 true
effect @p[scores={Pip=3}] haste 3 2 true
effect @p[scores={Pip=3}] jump_boost 3 1 true
effect @p[scores={Pip=3}] speed 3 1 true
effect @p[scores={Pip=4}] haste 3 3 true
effect @p[scores={Pip=4}] jump_boost 3 1 true
effect @p[scores={Pip=4}] speed 3 1 true
effect @p[scores={Pip=5}] haste 3 4 true
effect @p[scores={Pip=5}] jump_boost 3 1 true
effect @p[scores={Pip=5}] speed 3 1 true
effect @p[scores={Pip=6}] haste 3 5 true
effect @p[scores={Pip=6}] jump_boost 3 1 true
effect @p[scores={Pip=6}] speed 3 1 true
